### ISSUE TITLE
Deploying the code results in error related to AWS CodeCommit

### ISSUE THREAD

**Issue by skondoji2** [aws-solutions-library-samples/guidance-for-carbon-data-lake-on-aws#50]
We do have Azure devops Github account. How can we use our account instead?

**Comment by sathish0804** [comment]
11:12:03 PM | CREATE_FAILED        | AWS::CodeCommit::Repository | AmplifyDeploymentA...Repository38B61096
CreateRepository request is not allowed because there is no existing repository in this AWS account or AWS Organization (Service: AWSCodeCommit; Status Code: 400; Err
or Code: OperationNotAllowedException; Request ID: feaf61c4-3a5e-40b3-9da0-a058b19c1db6; Proxy: null)
 
 
❌  WebStack failed: Error: The stack named WebStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: CreateRepository request is not allowed because there is no existing repository in this AWS account or AWS Organization (Service: AWSCodeCommit; Status Code: 400; Error Code: OperationNotAllowedException; Request ID: feaf61c4-3a5e-40b3-9da0-a058b19c1db6; Proxy: null)
    at FullCloudFormationDeployment.monitorDeployment (/Users/satishvanga/.npm-global/lib/node_modules/aws-cdk/lib/index.js:452:10567)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/satishvanga/.npm-global/lib/node_modules/aws-cdk/lib/index.js:455:200276)
    at async /Users/satishvanga/.npm-global/lib/node_modules/aws-cdk/lib/index.js:455:181698
 
❌ Deployment failed: Error: The stack named WebStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: CreateRepository request is not allowed because there is no existing repository in this AWS account or AWS Organization (Service: AWSCodeCommit; Status Code: 400; Error Code: OperationNotAllowedException; Request ID: feaf61c4-3a5e-40b3-9da0-a058b19c1db6; Proxy: null)
    at FullCloudFormationDeployment.monitorDeployment (/Users/satishvanga/.npm-global/lib/node_modules/aws-cdk/lib/index.js:452:10567)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.deployStack2 [as deployStack] (/Users/satishvanga/.npm-global/lib/node_modules/aws-cdk/lib/index.js:455:200276)
    at async /Users/satishvanga/.npm-global/lib/node_modules/aws-cdk/lib/index.js:455:181698
 
The stack named WebStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: CreateRepository request is not allowed because there is no existing repository in this AWS account or AWS Organization (Service: AWSCodeCommit; Status Code: 400; Error Code:

**Comment by cmgabri** [comment]
> We do have Azure devops Github account. How can we use our account instead? When we deploy using cdk tool, is it trying to create repository for Web application in AWS CodeCommit? The error message is related to not supporting AWS CodeCommit for new users. How can we tell to use a different repository? From Readme. Web Stack Outputs -**cdlWebAppRepositoryLink**: Amplify Web Application codecommit repository link. -cdlWebAppId: Amplify Web Application ID. -cdlAmplifyLink: Amplify Web Application AWS Console URL. -cdlWebAppDomain: Amplify Web Application live web URL.

Beginning on July 25, 2024 AWS CodeCommit ceased onboarding new customers as you have pointed out. We do not currently have a timeline for updating this solution guidance to allow for deployment outside of CodeCommit.
